global:
  scrape_interval:     15s
  evaluation_interval: 15s


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'pihole'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9617']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

remote_write:
  - url: "http://10.50.17.18:3000"
    basic_auth:
      username: "admin"
      password: "admin"